from setuptools import setup

setup(
    name='zno_countdown_bot',
    version='1.0.0r',
    packages=['venv2.Lib.site-packages.PIL', 'venv2.Lib.site-packages.pip', 'venv2.Lib.site-packages.pip._vendor',
              'venv2.Lib.site-packages.pip._vendor.idna', 'venv2.Lib.site-packages.pip._vendor.pep517',
              'venv2.Lib.site-packages.pip._vendor.pytoml', 'venv2.Lib.site-packages.pip._vendor.certifi',
              'venv2.Lib.site-packages.pip._vendor.chardet', 'venv2.Lib.site-packages.pip._vendor.chardet.cli',
              'venv2.Lib.site-packages.pip._vendor.distlib', 'venv2.Lib.site-packages.pip._vendor.distlib._backport',
              'venv2.Lib.site-packages.pip._vendor.msgpack', 'venv2.Lib.site-packages.pip._vendor.urllib3',
              'venv2.Lib.site-packages.pip._vendor.urllib3.util', 'venv2.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv2.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv2.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv2.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv2.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv2.Lib.site-packages.pip._vendor.colorama', 'venv2.Lib.site-packages.pip._vendor.html5lib',
              'venv2.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv2.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv2.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv2.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv2.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'venv2.Lib.site-packages.pip._vendor.lockfile', 'venv2.Lib.site-packages.pip._vendor.progress',
              'venv2.Lib.site-packages.pip._vendor.requests', 'venv2.Lib.site-packages.pip._vendor.packaging',
              'venv2.Lib.site-packages.pip._vendor.cachecontrol',
              'venv2.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv2.Lib.site-packages.pip._vendor.webencodings', 'venv2.Lib.site-packages.pip._vendor.pkg_resources',
              'venv2.Lib.site-packages.pip._internal', 'venv2.Lib.site-packages.pip._internal.cli',
              'venv2.Lib.site-packages.pip._internal.req', 'venv2.Lib.site-packages.pip._internal.vcs',
              'venv2.Lib.site-packages.pip._internal.utils', 'venv2.Lib.site-packages.pip._internal.models',
              'venv2.Lib.site-packages.pip._internal.commands', 'venv2.Lib.site-packages.pip._internal.operations',
              'venv2.Lib.site-packages.cffi', 'venv2.Lib.site-packages.past', 'venv2.Lib.site-packages.past.tests',
              'venv2.Lib.site-packages.past.types', 'venv2.Lib.site-packages.past.utils',
              'venv2.Lib.site-packages.past.builtins', 'venv2.Lib.site-packages.past.translation',
              'venv2.Lib.site-packages.dotenv', 'venv2.Lib.site-packages.future',
              'venv2.Lib.site-packages.future.moves', 'venv2.Lib.site-packages.future.moves.dbm',
              'venv2.Lib.site-packages.future.moves.html', 'venv2.Lib.site-packages.future.moves.http',
              'venv2.Lib.site-packages.future.moves.test', 'venv2.Lib.site-packages.future.moves.urllib',
              'venv2.Lib.site-packages.future.moves.xmlrpc', 'venv2.Lib.site-packages.future.moves.tkinter',
              'venv2.Lib.site-packages.future.tests', 'venv2.Lib.site-packages.future.types',
              'venv2.Lib.site-packages.future.utils', 'venv2.Lib.site-packages.future.builtins',
              'venv2.Lib.site-packages.future.backports', 'venv2.Lib.site-packages.future.backports.html',
              'venv2.Lib.site-packages.future.backports.http', 'venv2.Lib.site-packages.future.backports.test',
              'venv2.Lib.site-packages.future.backports.email', 'venv2.Lib.site-packages.future.backports.email.mime',
              'venv2.Lib.site-packages.future.backports.urllib', 'venv2.Lib.site-packages.future.backports.xmlrpc',
              'venv2.Lib.site-packages.future.standard_library', 'venv2.Lib.site-packages.certifi',
              'venv2.Lib.site-packages.telegram', 'venv2.Lib.site-packages.telegram.ext',
              'venv2.Lib.site-packages.telegram.files', 'venv2.Lib.site-packages.telegram.games',
              'venv2.Lib.site-packages.telegram.utils', 'venv2.Lib.site-packages.telegram.inline',
              'venv2.Lib.site-packages.telegram.vendor', 'venv2.Lib.site-packages.telegram.vendor.ptb_urllib3',
              'venv2.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3',
              'venv2.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.util',
              'venv2.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.contrib',
              'venv2.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.packages',
              'venv2.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.packages.backports',
              'venv2.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.packages.ssl_match_hostname',
              'venv2.Lib.site-packages.telegram.payment', 'venv2.Lib.site-packages.telegram.passport',
              'venv2.Lib.site-packages.pycparser', 'venv2.Lib.site-packages.pycparser.ply',
              'venv2.Lib.site-packages.asn1crypto', 'venv2.Lib.site-packages.asn1crypto._perf',
              'venv2.Lib.site-packages.libfuturize', 'venv2.Lib.site-packages.libfuturize.fixes',
              'venv2.Lib.site-packages.cryptography', 'venv2.Lib.site-packages.cryptography.x509',
              'venv2.Lib.site-packages.cryptography.hazmat', 'venv2.Lib.site-packages.cryptography.hazmat.backends',
              'venv2.Lib.site-packages.cryptography.hazmat.backends.openssl',
              'venv2.Lib.site-packages.cryptography.hazmat.bindings',
              'venv2.Lib.site-packages.cryptography.hazmat.bindings.openssl',
              'venv2.Lib.site-packages.cryptography.hazmat.primitives',
              'venv2.Lib.site-packages.cryptography.hazmat.primitives.kdf',
              'venv2.Lib.site-packages.cryptography.hazmat.primitives.ciphers',
              'venv2.Lib.site-packages.cryptography.hazmat.primitives.twofactor',
              'venv2.Lib.site-packages.cryptography.hazmat.primitives.asymmetric',
              'venv2.Lib.site-packages.cryptography.hazmat.primitives.serialization',
              'venv2.Lib.site-packages.libpasteurize', 'venv2.Lib.site-packages.libpasteurize.fixes',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv2.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='',
    author='MrGra',
    author_email='',
    description=''
)
